# Generated by Django 4.1.5 on 2023-01-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('others', 'others')], max_length=100)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('p_number', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('addrss', models.CharField(blank=True, max_length=300, null=True)),
                ('dist', models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode')], max_length=100)),
                ('accounts', models.CharField(choices=[('savaing account', 'savaing account'), ('current account', 'current account'), ('checking account', 'checking account')], max_length=100)),
                ('materials', models.CharField(blank=True, choices=[('debit card', 'debit card'), ('credit card', 'credit card'), ('cheque', 'cheque')], max_length=200, null=True)),
            ],
        ),
    ]
